# Generated by Django 5.2.7 on 2025-10-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('entrepreneur', models.BooleanField(default=False, null=True, verbose_name='Si entrepreneur')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='email')),
                ('Address', models.CharField(max_length=1000, verbose_name='adresse')),
                ('activity_section', models.CharField(max_length=500, verbose_name="Secteur d'activités")),
                ('why', models.CharField(max_length=255, verbose_name='Raison de participation')),
                ('partner_or_sponsor', models.CharField(max_length=10, verbose_name='Sponsor ou partenaire')),
            ],
        ),
    ]
