# Generated by Django 5.2.7 on 2025-10-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_app', '0002_mailsender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='partner',
            name='about',
            field=models.CharField(default='', max_length=300, verbose_name='Poste en entreprise ou fonction metier'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='why',
            field=models.CharField(max_length=255, verbose_name='(Motivation)Raison de participation'),
        ),
    ]
